# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercice',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
