# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solving', '0002_auto_20171103_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
